<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/06/17 11:38:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=votainteligente_proyectos',
  'username' => 'vota_p',
  'password' => 'vota_754',
  'name' => 'doctrine',
)),);
