<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/06/17 13:08:51
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
);
