<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/06/17 15:03:07
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
);
