<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/06/17 13:36:02
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
  'show2' => 
  array (
    'is_secure' => false,
  ),
  'votaciones' => 
  array (
    'is_secure' => false,
  ),
);
