<?php

/**
 * BaseProyectoLeyEnComision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_proyecto_ley
 * @property integer $id_comision
 * 
 * @method integer               getIdProyectoLey()   Returns the current record's "id_proyecto_ley" value
 * @method integer               getIdComision()      Returns the current record's "id_comision" value
 * @method ProyectoLeyEnComision setIdProyectoLey()   Sets the current record's "id_proyecto_ley" value
 * @method ProyectoLeyEnComision setIdComision()      Sets the current record's "id_comision" value
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseProyectoLeyEnComision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ProyectoLeyEnComision');
        $this->hasColumn('id_proyecto_ley', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_comision', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}