<?php

/**
 * BaseAutor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_autor
 * @property string $nombre
 * @property string $apellidos
 * @property string $cargo
 * @property string $periodos
 * @property integer $id_parlamentario
 * @property Doctrine_Collection $AutorProyectoLey
 * @property Parlamentario $Parlamentario
 * 
 * @method integer             getIdAutor()          Returns the current record's "id_autor" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getApellidos()        Returns the current record's "apellidos" value
 * @method string              getCargo()            Returns the current record's "cargo" value
 * @method string              getPeriodos()         Returns the current record's "periodos" value
 * @method integer             getIdParlamentario()  Returns the current record's "id_parlamentario" value
 * @method Doctrine_Collection getAutorProyectoLey() Returns the current record's "AutorProyectoLey" collection
 * @method Parlamentario       getParlamentario()    Returns the current record's "Parlamentario" value
 * @method Autor               setIdAutor()          Sets the current record's "id_autor" value
 * @method Autor               setNombre()           Sets the current record's "nombre" value
 * @method Autor               setApellidos()        Sets the current record's "apellidos" value
 * @method Autor               setCargo()            Sets the current record's "cargo" value
 * @method Autor               setPeriodos()         Sets the current record's "periodos" value
 * @method Autor               setIdParlamentario()  Sets the current record's "id_parlamentario" value
 * @method Autor               setAutorProyectoLey() Sets the current record's "AutorProyectoLey" collection
 * @method Autor               setParlamentario()    Sets the current record's "Parlamentario" value
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseAutor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Autor');
        $this->hasColumn('id_autor', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('apellidos', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('cargo', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('periodos', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('id_parlamentario', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AutorProyectoLey', array(
             'local' => 'id_autor',
             'foreign' => 'id_autor',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Parlamentario', array(
             'local' => 'id_parlamentario',
             'foreign' => 'id_parlamentario'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}