<?php

/**
 * BaseSesion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_sesion
 * @property date $fecha
 * @property string $camara
 * @property integer $nro
 * @property Doctrine_Collection $ProyectoLey
 * @property Doctrine_Collection $Votacion
 * 
 * @method integer             getIdSesion()    Returns the current record's "id_sesion" value
 * @method date                getFecha()       Returns the current record's "fecha" value
 * @method string              getCamara()      Returns the current record's "camara" value
 * @method integer             getNro()         Returns the current record's "nro" value
 * @method Doctrine_Collection getProyectoLey() Returns the current record's "ProyectoLey" collection
 * @method Doctrine_Collection getVotacion()    Returns the current record's "Votacion" collection
 * @method Sesion              setIdSesion()    Sets the current record's "id_sesion" value
 * @method Sesion              setFecha()       Sets the current record's "fecha" value
 * @method Sesion              setCamara()      Sets the current record's "camara" value
 * @method Sesion              setNro()         Sets the current record's "nro" value
 * @method Sesion              setProyectoLey() Sets the current record's "ProyectoLey" collection
 * @method Sesion              setVotacion()    Sets the current record's "Votacion" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseSesion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Sesion');
        $this->hasColumn('id_sesion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('camara', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('nro', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProyectoLey', array(
             'refClass' => 'ProyectoLeyEnSesion',
             'local' => 'id_sesion',
             'foreign' => 'id_proyecto_ley',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Votacion', array(
             'local' => 'id_sesion',
             'foreign' => 'id_sesion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}