<?php

/**
 * BaseDebateComision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_debate
 * @property integer $id_comision
 * 
 * @method integer        getIdDebate()    Returns the current record's "id_debate" value
 * @method integer        getIdComision()  Returns the current record's "id_comision" value
 * @method DebateComision setIdDebate()    Sets the current record's "id_debate" value
 * @method DebateComision setIdComision()  Sets the current record's "id_comision" value
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseDebateComision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('DebateComision');
        $this->hasColumn('id_debate', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_comision', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}