<?php

/**
 * BaseVotacionParlamentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_votacion
 * @property integer $id_parlamentario
 * @property string $voto
 * 
 * @method integer               getIdVotacion()       Returns the current record's "id_votacion" value
 * @method integer               getIdParlamentario()  Returns the current record's "id_parlamentario" value
 * @method string                getVoto()             Returns the current record's "voto" value
 * @method VotacionParlamentario setIdVotacion()       Sets the current record's "id_votacion" value
 * @method VotacionParlamentario setIdParlamentario()  Sets the current record's "id_parlamentario" value
 * @method VotacionParlamentario setVoto()             Sets the current record's "voto" value
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseVotacionParlamentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('VotacionParlamentario');
        $this->hasColumn('id_votacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_parlamentario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('voto', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}