<?php

/**
 * BaseDistrito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_distrito
 * @property integer $id_circunscripcion
 * @property integer $id_region
 * @property Doctrine_Collection $Parlamentario
 * @property Circunscripcion $Circunscripcion
 * @property Region $Region
 * @property Doctrine_Collection $Comuna
 * 
 * @method integer             getIdDistrito()         Returns the current record's "id_distrito" value
 * @method integer             getIdCircunscripcion()  Returns the current record's "id_circunscripcion" value
 * @method integer             getIdRegion()           Returns the current record's "id_region" value
 * @method Doctrine_Collection getParlamentario()      Returns the current record's "Parlamentario" collection
 * @method Circunscripcion     getCircunscripcion()    Returns the current record's "Circunscripcion" value
 * @method Region              getRegion()             Returns the current record's "Region" value
 * @method Doctrine_Collection getComuna()             Returns the current record's "Comuna" collection
 * @method Distrito            setIdDistrito()         Sets the current record's "id_distrito" value
 * @method Distrito            setIdCircunscripcion()  Sets the current record's "id_circunscripcion" value
 * @method Distrito            setIdRegion()           Sets the current record's "id_region" value
 * @method Distrito            setParlamentario()      Sets the current record's "Parlamentario" collection
 * @method Distrito            setCircunscripcion()    Sets the current record's "Circunscripcion" value
 * @method Distrito            setRegion()             Sets the current record's "Region" value
 * @method Distrito            setComuna()             Sets the current record's "Comuna" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseDistrito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Distrito');
        $this->hasColumn('id_distrito', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_circunscripcion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_region', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parlamentario', array(
             'local' => 'id_distrito',
             'foreign' => 'id_distrito'));

        $this->hasOne('Circunscripcion', array(
             'local' => 'id_circunscripcion',
             'foreign' => 'id_circunscripcion'));

        $this->hasOne('Region', array(
             'local' => 'id_region',
             'foreign' => 'id_region'));

        $this->hasMany('Comuna', array(
             'local' => 'id_distrito',
             'foreign' => 'id_distrito'));
    }
}