<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_region
 * @property string $sigla
 * @property string $nombre
 * @property Doctrine_Collection $Distrito
 * 
 * @method integer             getIdRegion()  Returns the current record's "id_region" value
 * @method string              getSigla()     Returns the current record's "sigla" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getDistrito()  Returns the current record's "Distrito" collection
 * @method Region              setIdRegion()  Sets the current record's "id_region" value
 * @method Region              setSigla()     Sets the current record's "sigla" value
 * @method Region              setNombre()    Sets the current record's "nombre" value
 * @method Region              setDistrito()  Sets the current record's "Distrito" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Region');
        $this->hasColumn('id_region', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sigla', 'string', 4, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Distrito', array(
             'local' => 'id_region',
             'foreign' => 'id_region'));
    }
}