<?php

/**
 * BaseCircunscripcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_circunscripcion
 * @property string $nombre
 * @property Doctrine_Collection $Parlamentario
 * @property Doctrine_Collection $Distrito
 * 
 * @method integer             getIdCircunscripcion()  Returns the current record's "id_circunscripcion" value
 * @method string              getNombre()             Returns the current record's "nombre" value
 * @method Doctrine_Collection getParlamentario()      Returns the current record's "Parlamentario" collection
 * @method Doctrine_Collection getDistrito()           Returns the current record's "Distrito" collection
 * @method Circunscripcion     setIdCircunscripcion()  Sets the current record's "id_circunscripcion" value
 * @method Circunscripcion     setNombre()             Sets the current record's "nombre" value
 * @method Circunscripcion     setParlamentario()      Sets the current record's "Parlamentario" collection
 * @method Circunscripcion     setDistrito()           Sets the current record's "Distrito" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseCircunscripcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Circunscripcion');
        $this->hasColumn('id_circunscripcion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parlamentario', array(
             'local' => 'id_circunscripcion',
             'foreign' => 'id_circunscripcion'));

        $this->hasMany('Distrito', array(
             'local' => 'id_circunscripcion',
             'foreign' => 'id_circunscripcion'));
    }
}