<?php

/**
 * BaseComuna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_comuna
 * @property string $nombre
 * @property integer $id_distrito
 * @property Distrito $Distrito
 * 
 * @method integer  getIdComuna()    Returns the current record's "id_comuna" value
 * @method string   getNombre()      Returns the current record's "nombre" value
 * @method integer  getIdDistrito()  Returns the current record's "id_distrito" value
 * @method Distrito getDistrito()    Returns the current record's "Distrito" value
 * @method Comuna   setIdComuna()    Sets the current record's "id_comuna" value
 * @method Comuna   setNombre()      Sets the current record's "nombre" value
 * @method Comuna   setIdDistrito()  Sets the current record's "id_distrito" value
 * @method Comuna   setDistrito()    Sets the current record's "Distrito" value
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseComuna extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Comuna');
        $this->hasColumn('id_comuna', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('id_distrito', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Distrito', array(
             'local' => 'id_distrito',
             'foreign' => 'id_distrito'));
    }
}