<?php

/**
 * BaseProyectoLey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_proyecto_ley
 * @property string $nro_boletin
 * @property string $titulo
 * @property string $titulo_sesion
 * @property date $fecha_ingreso
 * @property string $iniciativa
 * @property string $tipo
 * @property string $camara_origen
 * @property string $urgencia
 * @property string $etapa
 * @property string $sub_etapa
 * @property integer $ley
 * @property string $ley_bcn
 * @property integer $decreto
 * @property string $decreto_bcn
 * @property date $fecha_publicacion
 * @property integer $id_materia
 * @property integer $nro_interno
 * @property integer $avance
 * @property integer $nro_tramitacion
 * @property string $tramitacion_act
 * @property string $resumen
 * @property Materia $Materia
 * @property Doctrine_Collection $AutorProyectoLey
 * @property Doctrine_Collection $Comision
 * @property Doctrine_Collection $Debate
 * @property Doctrine_Collection $Sesion
 * @property Doctrine_Collection $ProyectoLey
 * @property Doctrine_Collection $Votacion
 * @property Doctrine_Collection $VotacionComision
 * 
 * @method integer             getIdProyectoLey()     Returns the current record's "id_proyecto_ley" value
 * @method string              getNroBoletin()        Returns the current record's "nro_boletin" value
 * @method string              getTitulo()            Returns the current record's "titulo" value
 * @method string              getTituloSesion()      Returns the current record's "titulo_sesion" value
 * @method date                getFechaIngreso()      Returns the current record's "fecha_ingreso" value
 * @method string              getIniciativa()        Returns the current record's "iniciativa" value
 * @method string              getTipo()              Returns the current record's "tipo" value
 * @method string              getCamaraOrigen()      Returns the current record's "camara_origen" value
 * @method string              getUrgencia()          Returns the current record's "urgencia" value
 * @method string              getEtapa()             Returns the current record's "etapa" value
 * @method string              getSubEtapa()          Returns the current record's "sub_etapa" value
 * @method integer             getLey()               Returns the current record's "ley" value
 * @method string              getLeyBcn()            Returns the current record's "ley_bcn" value
 * @method integer             getDecreto()           Returns the current record's "decreto" value
 * @method string              getDecretoBcn()        Returns the current record's "decreto_bcn" value
 * @method date                getFechaPublicacion()  Returns the current record's "fecha_publicacion" value
 * @method integer             getIdMateria()         Returns the current record's "id_materia" value
 * @method integer             getNroInterno()        Returns the current record's "nro_interno" value
 * @method integer             getAvance()            Returns the current record's "avance" value
 * @method integer             getNroTramitacion()    Returns the current record's "nro_tramitacion" value
 * @method string              getTramitacionAct()    Returns the current record's "tramitacion_act" value
 * @method string              getResumen()           Returns the current record's "resumen" value
 * @method Materia             getMateria()           Returns the current record's "Materia" value
 * @method Doctrine_Collection getAutorProyectoLey()  Returns the current record's "AutorProyectoLey" collection
 * @method Doctrine_Collection getComision()          Returns the current record's "Comision" collection
 * @method Doctrine_Collection getDebate()            Returns the current record's "Debate" collection
 * @method Doctrine_Collection getSesion()            Returns the current record's "Sesion" collection
 * @method Doctrine_Collection getProyectoLey()       Returns the current record's "ProyectoLey" collection
 * @method Doctrine_Collection getVotacion()          Returns the current record's "Votacion" collection
 * @method Doctrine_Collection getVotacionComision()  Returns the current record's "VotacionComision" collection
 * @method ProyectoLey         setIdProyectoLey()     Sets the current record's "id_proyecto_ley" value
 * @method ProyectoLey         setNroBoletin()        Sets the current record's "nro_boletin" value
 * @method ProyectoLey         setTitulo()            Sets the current record's "titulo" value
 * @method ProyectoLey         setTituloSesion()      Sets the current record's "titulo_sesion" value
 * @method ProyectoLey         setFechaIngreso()      Sets the current record's "fecha_ingreso" value
 * @method ProyectoLey         setIniciativa()        Sets the current record's "iniciativa" value
 * @method ProyectoLey         setTipo()              Sets the current record's "tipo" value
 * @method ProyectoLey         setCamaraOrigen()      Sets the current record's "camara_origen" value
 * @method ProyectoLey         setUrgencia()          Sets the current record's "urgencia" value
 * @method ProyectoLey         setEtapa()             Sets the current record's "etapa" value
 * @method ProyectoLey         setSubEtapa()          Sets the current record's "sub_etapa" value
 * @method ProyectoLey         setLey()               Sets the current record's "ley" value
 * @method ProyectoLey         setLeyBcn()            Sets the current record's "ley_bcn" value
 * @method ProyectoLey         setDecreto()           Sets the current record's "decreto" value
 * @method ProyectoLey         setDecretoBcn()        Sets the current record's "decreto_bcn" value
 * @method ProyectoLey         setFechaPublicacion()  Sets the current record's "fecha_publicacion" value
 * @method ProyectoLey         setIdMateria()         Sets the current record's "id_materia" value
 * @method ProyectoLey         setNroInterno()        Sets the current record's "nro_interno" value
 * @method ProyectoLey         setAvance()            Sets the current record's "avance" value
 * @method ProyectoLey         setNroTramitacion()    Sets the current record's "nro_tramitacion" value
 * @method ProyectoLey         setTramitacionAct()    Sets the current record's "tramitacion_act" value
 * @method ProyectoLey         setResumen()           Sets the current record's "resumen" value
 * @method ProyectoLey         setMateria()           Sets the current record's "Materia" value
 * @method ProyectoLey         setAutorProyectoLey()  Sets the current record's "AutorProyectoLey" collection
 * @method ProyectoLey         setComision()          Sets the current record's "Comision" collection
 * @method ProyectoLey         setDebate()            Sets the current record's "Debate" collection
 * @method ProyectoLey         setSesion()            Sets the current record's "Sesion" collection
 * @method ProyectoLey         setProyectoLey()       Sets the current record's "ProyectoLey" collection
 * @method ProyectoLey         setVotacion()          Sets the current record's "Votacion" collection
 * @method ProyectoLey         setVotacionComision()  Sets the current record's "VotacionComision" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseProyectoLey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ProyectoLey');
        $this->hasColumn('id_proyecto_ley', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nro_boletin', 'string', 10, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('titulo', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '500',
             ));
        $this->hasColumn('titulo_sesion', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('fecha_ingreso', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('iniciativa', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('tipo', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('camara_origen', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('urgencia', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('etapa', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('sub_etapa', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('ley', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ley_bcn', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('decreto', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('decreto_bcn', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('fecha_publicacion', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('id_materia', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nro_interno', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('avance', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('nro_tramitacion', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tramitacion_act', 'string', 2, array(
             'type' => 'string',
             'length' => '2',
             ));
        $this->hasColumn('resumen', 'string', 5000, array(
             'type' => 'string',
             'length' => '5000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Materia', array(
             'local' => 'id_materia',
             'foreign' => 'id_materia'));

        $this->hasMany('AutorProyectoLey', array(
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_proyecto_ley',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Comision', array(
             'refClass' => 'ProyectoLeyEnComision',
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_comision',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Debate', array(
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_proyecto_ley'));

        $this->hasMany('Sesion', array(
             'refClass' => 'ProyectoLeyEnSesion',
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_sesion',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('ProyectoLey', array(
             'refClass' => 'ProyectoLeyRefundido',
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_proyecto_ley2'));

        $this->hasMany('Votacion', array(
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_proyecto_ley'));

        $this->hasMany('VotacionComision', array(
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_proyecto_ley'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}