<?php

/**
 * BaseParlamentarioEnComision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_parlamentario
 * @property integer $id_comision
 * @property string $cargo
 * 
 * @method integer                 getIdParlamentario()  Returns the current record's "id_parlamentario" value
 * @method integer                 getIdComision()       Returns the current record's "id_comision" value
 * @method string                  getCargo()            Returns the current record's "cargo" value
 * @method ParlamentarioEnComision setIdParlamentario()  Sets the current record's "id_parlamentario" value
 * @method ParlamentarioEnComision setIdComision()       Sets the current record's "id_comision" value
 * @method ParlamentarioEnComision setCargo()            Sets the current record's "cargo" value
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseParlamentarioEnComision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ParlamentarioEnComision');
        $this->hasColumn('id_parlamentario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_comision', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('cargo', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}