<?php

/**
 * BaseVotacionComisionParlamentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_votacion
 * @property integer $id_parlamentario
 * @property string $voto
 * @property VotacionComision $VotacionComision
 * @property Parlamentario $Parlamentario
 * 
 * @method integer                       getIdVotacion()       Returns the current record's "id_votacion" value
 * @method integer                       getIdParlamentario()  Returns the current record's "id_parlamentario" value
 * @method string                        getVoto()             Returns the current record's "voto" value
 * @method VotacionComision              getVotacionComision() Returns the current record's "VotacionComision" value
 * @method Parlamentario                 getParlamentario()    Returns the current record's "Parlamentario" value
 * @method VotacionComisionParlamentario setIdVotacion()       Sets the current record's "id_votacion" value
 * @method VotacionComisionParlamentario setIdParlamentario()  Sets the current record's "id_parlamentario" value
 * @method VotacionComisionParlamentario setVoto()             Sets the current record's "voto" value
 * @method VotacionComisionParlamentario setVotacionComision() Sets the current record's "VotacionComision" value
 * @method VotacionComisionParlamentario setParlamentario()    Sets the current record's "Parlamentario" value
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseVotacionComisionParlamentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('VotacionComisionParlamentario');
        $this->hasColumn('id_votacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id_parlamentario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('voto', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VotacionComision', array(
             'local' => 'id_votacion',
             'foreign' => 'id_votacion'));

        $this->hasOne('Parlamentario', array(
             'local' => 'id_parlamentario',
             'foreign' => 'id_parlamentario'));
    }
}