<?php

/**
 * BaseComision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_comision
 * @property string $nombre
 * @property string $tipo
 * @property string $camara
 * @property string $contacto_mail
 * @property string $contacto_tel
 * @property string $contacto_form
 * @property string $abogado_secretario
 * @property string $abogado_ayudante
 * @property string $secretario_ejecutivo
 * @property Doctrine_Collection $Debate
 * @property Doctrine_Collection $Parlamentario
 * @property Doctrine_Collection $ProyectoLey
 * 
 * @method integer             getIdComision()           Returns the current record's "id_comision" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method string              getTipo()                 Returns the current record's "tipo" value
 * @method string              getCamara()               Returns the current record's "camara" value
 * @method string              getContactoMail()         Returns the current record's "contacto_mail" value
 * @method string              getContactoTel()          Returns the current record's "contacto_tel" value
 * @method string              getContactoForm()         Returns the current record's "contacto_form" value
 * @method string              getAbogadoSecretario()    Returns the current record's "abogado_secretario" value
 * @method string              getAbogadoAyudante()      Returns the current record's "abogado_ayudante" value
 * @method string              getSecretarioEjecutivo()  Returns the current record's "secretario_ejecutivo" value
 * @method Doctrine_Collection getDebate()               Returns the current record's "Debate" collection
 * @method Doctrine_Collection getParlamentario()        Returns the current record's "Parlamentario" collection
 * @method Doctrine_Collection getProyectoLey()          Returns the current record's "ProyectoLey" collection
 * @method Comision            setIdComision()           Sets the current record's "id_comision" value
 * @method Comision            setNombre()               Sets the current record's "nombre" value
 * @method Comision            setTipo()                 Sets the current record's "tipo" value
 * @method Comision            setCamara()               Sets the current record's "camara" value
 * @method Comision            setContactoMail()         Sets the current record's "contacto_mail" value
 * @method Comision            setContactoTel()          Sets the current record's "contacto_tel" value
 * @method Comision            setContactoForm()         Sets the current record's "contacto_form" value
 * @method Comision            setAbogadoSecretario()    Sets the current record's "abogado_secretario" value
 * @method Comision            setAbogadoAyudante()      Sets the current record's "abogado_ayudante" value
 * @method Comision            setSecretarioEjecutivo()  Sets the current record's "secretario_ejecutivo" value
 * @method Comision            setDebate()               Sets the current record's "Debate" collection
 * @method Comision            setParlamentario()        Sets the current record's "Parlamentario" collection
 * @method Comision            setProyectoLey()          Sets the current record's "ProyectoLey" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseComision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Comision');
        $this->hasColumn('id_comision', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('tipo', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('camara', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('contacto_mail', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('contacto_tel', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('contacto_form', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('abogado_secretario', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('abogado_ayudante', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('secretario_ejecutivo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Debate', array(
             'refClass' => 'DebateComision',
             'local' => 'id_comision',
             'foreign' => 'id_debate'));

        $this->hasMany('Parlamentario', array(
             'refClass' => 'ParlamentarioEnComision',
             'local' => 'id_comision',
             'foreign' => 'id_parlamentario',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('ProyectoLey', array(
             'refClass' => 'ProyectoLeyEnComision',
             'local' => 'id_comision',
             'foreign' => 'id_proyecto_ley',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}