<?php

/**
 * BaseVotacionComision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_votacion
 * @property integer $id_comision
 * @property string $camara
 * @property string $tipo
 * @property string $articulo
 * @property integer $voto_si
 * @property integer $voto_no
 * @property integer $voto_abs
 * @property integer $voto_disp
 * @property integer $voto_pareos
 * @property integer $voto_aus
 * @property string $resultado
 * @property string $quorum
 * @property integer $id_proyecto_ley
 * @property integer $id_debate
 * @property Comision $Comision
 * @property ProyectoLey $ProyectoLey
 * @property Debate $Debate
 * @property Doctrine_Collection $Parlamentario
 * @property Doctrine_Collection $VotacionComisionParlamentario
 * 
 * @method integer             getIdVotacion()                    Returns the current record's "id_votacion" value
 * @method integer             getIdComision()                    Returns the current record's "id_comision" value
 * @method string              getCamara()                        Returns the current record's "camara" value
 * @method string              getTipo()                          Returns the current record's "tipo" value
 * @method string              getArticulo()                      Returns the current record's "articulo" value
 * @method integer             getVotoSi()                        Returns the current record's "voto_si" value
 * @method integer             getVotoNo()                        Returns the current record's "voto_no" value
 * @method integer             getVotoAbs()                       Returns the current record's "voto_abs" value
 * @method integer             getVotoDisp()                      Returns the current record's "voto_disp" value
 * @method integer             getVotoPareos()                    Returns the current record's "voto_pareos" value
 * @method integer             getVotoAus()                       Returns the current record's "voto_aus" value
 * @method string              getResultado()                     Returns the current record's "resultado" value
 * @method string              getQuorum()                        Returns the current record's "quorum" value
 * @method integer             getIdProyectoLey()                 Returns the current record's "id_proyecto_ley" value
 * @method integer             getIdDebate()                      Returns the current record's "id_debate" value
 * @method Comision            getComision()                      Returns the current record's "Comision" value
 * @method ProyectoLey         getProyectoLey()                   Returns the current record's "ProyectoLey" value
 * @method Debate              getDebate()                        Returns the current record's "Debate" value
 * @method Doctrine_Collection getParlamentario()                 Returns the current record's "Parlamentario" collection
 * @method Doctrine_Collection getVotacionComisionParlamentario() Returns the current record's "VotacionComisionParlamentario" collection
 * @method VotacionComision    setIdVotacion()                    Sets the current record's "id_votacion" value
 * @method VotacionComision    setIdComision()                    Sets the current record's "id_comision" value
 * @method VotacionComision    setCamara()                        Sets the current record's "camara" value
 * @method VotacionComision    setTipo()                          Sets the current record's "tipo" value
 * @method VotacionComision    setArticulo()                      Sets the current record's "articulo" value
 * @method VotacionComision    setVotoSi()                        Sets the current record's "voto_si" value
 * @method VotacionComision    setVotoNo()                        Sets the current record's "voto_no" value
 * @method VotacionComision    setVotoAbs()                       Sets the current record's "voto_abs" value
 * @method VotacionComision    setVotoDisp()                      Sets the current record's "voto_disp" value
 * @method VotacionComision    setVotoPareos()                    Sets the current record's "voto_pareos" value
 * @method VotacionComision    setVotoAus()                       Sets the current record's "voto_aus" value
 * @method VotacionComision    setResultado()                     Sets the current record's "resultado" value
 * @method VotacionComision    setQuorum()                        Sets the current record's "quorum" value
 * @method VotacionComision    setIdProyectoLey()                 Sets the current record's "id_proyecto_ley" value
 * @method VotacionComision    setIdDebate()                      Sets the current record's "id_debate" value
 * @method VotacionComision    setComision()                      Sets the current record's "Comision" value
 * @method VotacionComision    setProyectoLey()                   Sets the current record's "ProyectoLey" value
 * @method VotacionComision    setDebate()                        Sets the current record's "Debate" value
 * @method VotacionComision    setParlamentario()                 Sets the current record's "Parlamentario" collection
 * @method VotacionComision    setVotacionComisionParlamentario() Sets the current record's "VotacionComisionParlamentario" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseVotacionComision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('VotacionComision');
        $this->hasColumn('id_votacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('id_comision', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('camara', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('tipo', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('articulo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('voto_si', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('voto_no', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('voto_abs', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('voto_disp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('voto_pareos', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('voto_aus', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('resultado', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('quorum', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('comentario', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('id_proyecto_ley', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_debate', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comision', array(
             'local' => 'id_comision',
             'foreign' => 'id_comision'));

        $this->hasOne('ProyectoLey', array(
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_proyecto_ley'));

        $this->hasOne('Debate', array(
             'local' => 'id_debate',
             'foreign' => 'id_debate'));

        $this->hasMany('Parlamentario', array(
             'refClass' => 'VotacionComisionParlamentario',
             'local' => 'id_votacion',
             'foreign' => 'id_parlamentario',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('VotacionComisionParlamentario', array(
             'local' => 'id_votacion',
             'foreign' => 'id_votacion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}
