<?php

/**
 * BaseParlamentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_parlamentario
 * @property string $nombre
 * @property string $apellidos
 * @property string $senador_diputado
 * @property integer $id_circunscripcion
 * @property integer $id_distrito
 * @property string $pacto
 * @property integer $id_partido
 * @property string $sexo
 * @property date $fecha_nacimiento
 * @property string $profesion
 * @property string $mesa_directiva
 * @property integer $periodos_senador
 * @property integer $periodos_diputado
 * @property string $periodos_senador_desc
 * @property string $periodos_diputado_desc
 * @property string $primera_vez
 * @property string $comisiones_anteriores
 * @property string $comisiones_actuales
 * @property integer $voto_nro
 * @property float $voto_porcentaje
 * @property integer $gasto_electoral2005
 * @property integer $financiamiento_electoral2005
 * @property integer $gasto_electoral2009
 * @property integer $financiamiento_electoral2009
 * @property string $comite_parlamentario
 * @property string $mail
 * @property string $web
 * @property string $twitter
 * @property string $facebook
 * @property integer $dietas
 * @property string $declaracion_interes
 * @property string $declaracion_patrimonio
 * @property string $educacion_universitaria
 * @property string $educacion_postgrado
 * @property string $cargos_gobierno
 * @property string $cargos_eleccion
 * @property string $experiencia_politica
 * @property string $experiencia_laboral
 * @property integer $id_parlamento
 * @property integer $activo
 * @property Doctrine_Collection $Autor
 * @property Distrito $Distrito
 * @property Circunscripcion $Circunscripcion
 * @property Partido $Partido
 * @property Doctrine_Collection $Votacion
 * @property Doctrine_Collection $VotacionComision
 * @property Doctrine_Collection $Comision
 * @property Doctrine_Collection $VotacionComisionParlamentario
 * 
 * @method integer             getIdParlamentario()               Returns the current record's "id_parlamentario" value
 * @method string              getNombre()                        Returns the current record's "nombre" value
 * @method string              getApellidos()                     Returns the current record's "apellidos" value
 * @method string              getSenadorDiputado()               Returns the current record's "senador_diputado" value
 * @method integer             getIdCircunscripcion()             Returns the current record's "id_circunscripcion" value
 * @method integer             getIdDistrito()                    Returns the current record's "id_distrito" value
 * @method string              getPacto()                         Returns the current record's "pacto" value
 * @method integer             getIdPartido()                     Returns the current record's "id_partido" value
 * @method string              getSexo()                          Returns the current record's "sexo" value
 * @method date                getFechaNacimiento()               Returns the current record's "fecha_nacimiento" value
 * @method string              getProfesion()                     Returns the current record's "profesion" value
 * @method string              getMesaDirectiva()                 Returns the current record's "mesa_directiva" value
 * @method integer             getPeriodosSenador()               Returns the current record's "periodos_senador" value
 * @method integer             getPeriodosDiputado()              Returns the current record's "periodos_diputado" value
 * @method string              getPeriodosSenadorDesc()           Returns the current record's "periodos_senador_desc" value
 * @method string              getPeriodosDiputadoDesc()          Returns the current record's "periodos_diputado_desc" value
 * @method string              getPrimeraVez()                    Returns the current record's "primera_vez" value
 * @method string              getComisionesAnteriores()          Returns the current record's "comisiones_anteriores" value
 * @method string              getComisionesActuales()            Returns the current record's "comisiones_actuales" value
 * @method integer             getVotoNro()                       Returns the current record's "voto_nro" value
 * @method float               getVotoPorcentaje()                Returns the current record's "voto_porcentaje" value
 * @method integer             getGastoElectoral2005()            Returns the current record's "gasto_electoral2005" value
 * @method integer             getFinanciamientoElectoral2005()   Returns the current record's "financiamiento_electoral2005" value
 * @method integer             getGastoElectoral2009()            Returns the current record's "gasto_electoral2009" value
 * @method integer             getFinanciamientoElectoral2009()   Returns the current record's "financiamiento_electoral2009" value
 * @method string              getComiteParlamentario()           Returns the current record's "comite_parlamentario" value
 * @method string              getMail()                          Returns the current record's "mail" value
 * @method string              getWeb()                           Returns the current record's "web" value
 * @method string              getTwitter()                       Returns the current record's "twitter" value
 * @method string              getFacebook()                      Returns the current record's "facebook" value
 * @method integer             getDietas()                        Returns the current record's "dietas" value
 * @method string              getDeclaracionInteres()            Returns the current record's "declaracion_interes" value
 * @method string              getDeclaracionPatrimonio()         Returns the current record's "declaracion_patrimonio" value
 * @method string              getEducacionUniversitaria()        Returns the current record's "educacion_universitaria" value
 * @method string              getEducacionPostgrado()            Returns the current record's "educacion_postgrado" value
 * @method string              getCargosGobierno()                Returns the current record's "cargos_gobierno" value
 * @method string              getCargosEleccion()                Returns the current record's "cargos_eleccion" value
 * @method string              getExperienciaPolitica()           Returns the current record's "experiencia_politica" value
 * @method string              getExperienciaLaboral()            Returns the current record's "experiencia_laboral" value
 * @method integer             getIdParlamento()                  Returns the current record's "id_parlamento" value
 * @method integer             getActivo()                        Returns the current record's "activo" value
 * @method Doctrine_Collection getAutor()                         Returns the current record's "Autor" collection
 * @method Distrito            getDistrito()                      Returns the current record's "Distrito" value
 * @method Circunscripcion     getCircunscripcion()               Returns the current record's "Circunscripcion" value
 * @method Partido             getPartido()                       Returns the current record's "Partido" value
 * @method Doctrine_Collection getVotacion()                      Returns the current record's "Votacion" collection
 * @method Doctrine_Collection getVotacionComision()              Returns the current record's "VotacionComision" collection
 * @method Doctrine_Collection getComision()                      Returns the current record's "Comision" collection
 * @method Doctrine_Collection getVotacionComisionParlamentario() Returns the current record's "VotacionComisionParlamentario" collection
 * @method Parlamentario       setIdParlamentario()               Sets the current record's "id_parlamentario" value
 * @method Parlamentario       setNombre()                        Sets the current record's "nombre" value
 * @method Parlamentario       setApellidos()                     Sets the current record's "apellidos" value
 * @method Parlamentario       setSenadorDiputado()               Sets the current record's "senador_diputado" value
 * @method Parlamentario       setIdCircunscripcion()             Sets the current record's "id_circunscripcion" value
 * @method Parlamentario       setIdDistrito()                    Sets the current record's "id_distrito" value
 * @method Parlamentario       setPacto()                         Sets the current record's "pacto" value
 * @method Parlamentario       setIdPartido()                     Sets the current record's "id_partido" value
 * @method Parlamentario       setSexo()                          Sets the current record's "sexo" value
 * @method Parlamentario       setFechaNacimiento()               Sets the current record's "fecha_nacimiento" value
 * @method Parlamentario       setProfesion()                     Sets the current record's "profesion" value
 * @method Parlamentario       setMesaDirectiva()                 Sets the current record's "mesa_directiva" value
 * @method Parlamentario       setPeriodosSenador()               Sets the current record's "periodos_senador" value
 * @method Parlamentario       setPeriodosDiputado()              Sets the current record's "periodos_diputado" value
 * @method Parlamentario       setPeriodosSenadorDesc()           Sets the current record's "periodos_senador_desc" value
 * @method Parlamentario       setPeriodosDiputadoDesc()          Sets the current record's "periodos_diputado_desc" value
 * @method Parlamentario       setPrimeraVez()                    Sets the current record's "primera_vez" value
 * @method Parlamentario       setComisionesAnteriores()          Sets the current record's "comisiones_anteriores" value
 * @method Parlamentario       setComisionesActuales()            Sets the current record's "comisiones_actuales" value
 * @method Parlamentario       setVotoNro()                       Sets the current record's "voto_nro" value
 * @method Parlamentario       setVotoPorcentaje()                Sets the current record's "voto_porcentaje" value
 * @method Parlamentario       setGastoElectoral2005()            Sets the current record's "gasto_electoral2005" value
 * @method Parlamentario       setFinanciamientoElectoral2005()   Sets the current record's "financiamiento_electoral2005" value
 * @method Parlamentario       setGastoElectoral2009()            Sets the current record's "gasto_electoral2009" value
 * @method Parlamentario       setFinanciamientoElectoral2009()   Sets the current record's "financiamiento_electoral2009" value
 * @method Parlamentario       setComiteParlamentario()           Sets the current record's "comite_parlamentario" value
 * @method Parlamentario       setMail()                          Sets the current record's "mail" value
 * @method Parlamentario       setWeb()                           Sets the current record's "web" value
 * @method Parlamentario       setTwitter()                       Sets the current record's "twitter" value
 * @method Parlamentario       setFacebook()                      Sets the current record's "facebook" value
 * @method Parlamentario       setDietas()                        Sets the current record's "dietas" value
 * @method Parlamentario       setDeclaracionInteres()            Sets the current record's "declaracion_interes" value
 * @method Parlamentario       setDeclaracionPatrimonio()         Sets the current record's "declaracion_patrimonio" value
 * @method Parlamentario       setEducacionUniversitaria()        Sets the current record's "educacion_universitaria" value
 * @method Parlamentario       setEducacionPostgrado()            Sets the current record's "educacion_postgrado" value
 * @method Parlamentario       setCargosGobierno()                Sets the current record's "cargos_gobierno" value
 * @method Parlamentario       setCargosEleccion()                Sets the current record's "cargos_eleccion" value
 * @method Parlamentario       setExperienciaPolitica()           Sets the current record's "experiencia_politica" value
 * @method Parlamentario       setExperienciaLaboral()            Sets the current record's "experiencia_laboral" value
 * @method Parlamentario       setIdParlamento()                  Sets the current record's "id_parlamento" value
 * @method Parlamentario       setActivo()                        Sets the current record's "activo" value
 * @method Parlamentario       setAutor()                         Sets the current record's "Autor" collection
 * @method Parlamentario       setDistrito()                      Sets the current record's "Distrito" value
 * @method Parlamentario       setCircunscripcion()               Sets the current record's "Circunscripcion" value
 * @method Parlamentario       setPartido()                       Sets the current record's "Partido" value
 * @method Parlamentario       setVotacion()                      Sets the current record's "Votacion" collection
 * @method Parlamentario       setVotacionComision()              Sets the current record's "VotacionComision" collection
 * @method Parlamentario       setComision()                      Sets the current record's "Comision" collection
 * @method Parlamentario       setVotacionComisionParlamentario() Sets the current record's "VotacionComisionParlamentario" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseParlamentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Parlamentario');
        $this->hasColumn('id_parlamentario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('apellidos', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('senador_diputado', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('id_circunscripcion', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_distrito', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pacto', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('id_partido', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1',
             ));
        $this->hasColumn('fecha_nacimiento', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('profesion', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('mesa_directiva', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('periodos_senador', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('periodos_diputado', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('periodos_senador_desc', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('periodos_diputado_desc', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('primera_vez', 'string', 2, array(
             'type' => 'string',
             'length' => '2',
             ));
        $this->hasColumn('comisiones_anteriores', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('comisiones_actuales', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('voto_nro', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('voto_porcentaje', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('gasto_electoral2005', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('financiamiento_electoral2005', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('gasto_electoral2009', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('financiamiento_electoral2009', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('comite_parlamentario', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('mail', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('web', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('twitter', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('facebook', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('dietas', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('declaracion_interes', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('declaracion_patrimonio', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('educacion_universitaria', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('educacion_postgrado', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('cargos_gobierno', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('cargos_eleccion', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('experiencia_politica', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('experiencia_laboral', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('id_parlamento', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('activo', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Autor', array(
             'local' => 'id_parlamentario',
             'foreign' => 'id_parlamentario'));

        $this->hasOne('Distrito', array(
             'local' => 'id_distrito',
             'foreign' => 'id_distrito'));

        $this->hasOne('Circunscripcion', array(
             'local' => 'id_circunscripcion',
             'foreign' => 'id_circunscripcion'));

        $this->hasOne('Partido', array(
             'local' => 'id_partido',
             'foreign' => 'id_partido'));

        $this->hasMany('Votacion', array(
             'refClass' => 'VotacionParlamentario',
             'local' => 'id_parlamentario',
             'foreign' => 'id_votacion',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('VotacionComision', array(
             'refClass' => 'VotacionComisionParlamentario',
             'local' => 'id_parlamentario',
             'foreign' => 'id_votacion',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Comision', array(
             'refClass' => 'ParlamentarioEnComision',
             'local' => 'id_parlamentario',
             'foreign' => 'id_comision',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('VotacionComisionParlamentario', array(
             'local' => 'id_parlamentario',
             'foreign' => 'id_parlamentario'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}