<?php

/**
 * BaseVotacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_votacion
 * @property string $name
 * @property string $camara
 * @property integer $en_sala
 * @property string $tipo
 * @property string $articulo
 * @property string $materia
 * @property date $fecha
 * @property time $hora
 * @property integer $voto_si
 * @property integer $voto_no
 * @property integer $voto_abs
 * @property integer $voto_disp
 * @property integer $voto_pareos
 * @property integer $voto_aus
 * @property string $resultado
 * @property string $quorum
 * @property integer $id_proyecto_ley
 * @property integer $id_sesion
 * @property integer $id_parlamento
 * @property integer $visible
 * @property ProyectoLey $ProyectoLey
 * @property Sesion $Sesion
 * @property Debate $Debate
 * @property Doctrine_Collection $Parlamentario
 * 
 * @method integer             getIdVotacion()      Returns the current record's "id_votacion" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getCamara()          Returns the current record's "camara" value
 * @method integer             getEnSala()          Returns the current record's "en_sala" value
 * @method string              getTipo()            Returns the current record's "tipo" value
 * @method string              getArticulo()        Returns the current record's "articulo" value
 * @method string              getMateria()         Returns the current record's "materia" value
 * @method date                getFecha()           Returns the current record's "fecha" value
 * @method time                getHora()            Returns the current record's "hora" value
 * @method integer             getVotoSi()          Returns the current record's "voto_si" value
 * @method integer             getVotoNo()          Returns the current record's "voto_no" value
 * @method integer             getVotoAbs()         Returns the current record's "voto_abs" value
 * @method integer             getVotoDisp()        Returns the current record's "voto_disp" value
 * @method integer             getVotoPareos()      Returns the current record's "voto_pareos" value
 * @method integer             getVotoAus()         Returns the current record's "voto_aus" value
 * @method string              getResultado()       Returns the current record's "resultado" value
 * @method string              getQuorum()          Returns the current record's "quorum" value
 * @method integer             getIdProyectoLey()   Returns the current record's "id_proyecto_ley" value
 * @method integer             getIdSesion()        Returns the current record's "id_sesion" value
 * @method integer             getIdParlamento()    Returns the current record's "id_parlamento" value
 * @method integer             getVisible()         Returns the current record's "visible" value
 * @method ProyectoLey         getProyectoLey()     Returns the current record's "ProyectoLey" value
 * @method Sesion              getSesion()          Returns the current record's "Sesion" value
 * @method Debate              getDebate()          Returns the current record's "Debate" value
 * @method Doctrine_Collection getParlamentario()   Returns the current record's "Parlamentario" collection
 * @method Votacion            setIdVotacion()      Sets the current record's "id_votacion" value
 * @method Votacion            setName()            Sets the current record's "name" value
 * @method Votacion            setCamara()          Sets the current record's "camara" value
 * @method Votacion            setEnSala()          Sets the current record's "en_sala" value
 * @method Votacion            setTipo()            Sets the current record's "tipo" value
 * @method Votacion            setArticulo()        Sets the current record's "articulo" value
 * @method Votacion            setMateria()         Sets the current record's "materia" value
 * @method Votacion            setFecha()           Sets the current record's "fecha" value
 * @method Votacion            setHora()            Sets the current record's "hora" value
 * @method Votacion            setVotoSi()          Sets the current record's "voto_si" value
 * @method Votacion            setVotoNo()          Sets the current record's "voto_no" value
 * @method Votacion            setVotoAbs()         Sets the current record's "voto_abs" value
 * @method Votacion            setVotoDisp()        Sets the current record's "voto_disp" value
 * @method Votacion            setVotoPareos()      Sets the current record's "voto_pareos" value
 * @method Votacion            setVotoAus()         Sets the current record's "voto_aus" value
 * @method Votacion            setResultado()       Sets the current record's "resultado" value
 * @method Votacion            setQuorum()          Sets the current record's "quorum" value
 * @method Votacion            setIdProyectoLey()   Sets the current record's "id_proyecto_ley" value
 * @method Votacion            setIdSesion()        Sets the current record's "id_sesion" value
 * @method Votacion            setIdParlamento()    Sets the current record's "id_parlamento" value
 * @method Votacion            setVisible()         Sets the current record's "visible" value
 * @method Votacion            setProyectoLey()     Sets the current record's "ProyectoLey" value
 * @method Votacion            setSesion()          Sets the current record's "Sesion" value
 * @method Votacion            setDebate()          Sets the current record's "Debate" value
 * @method Votacion            setParlamentario()   Sets the current record's "Parlamentario" collection
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseVotacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Votacion');
        $this->hasColumn('id_votacion', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('camara', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('en_sala', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('tipo', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('articulo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('materia', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hora', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('voto_si', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('voto_no', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('voto_abs', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('voto_disp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('voto_pareos', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('voto_aus', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('resultado', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('quorum', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('id_proyecto_ley', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_sesion', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_parlamento', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('visible', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProyectoLey', array(
             'local' => 'id_proyecto_ley',
             'foreign' => 'id_proyecto_ley'));

        $this->hasOne('Sesion', array(
             'local' => 'id_sesion',
             'foreign' => 'id_sesion'));

        $this->hasOne('Debate', array(
             'local' => 'id_debate',
             'foreign' => 'id_debate'));

        $this->hasMany('Parlamentario', array(
             'refClass' => 'VotacionParlamentario',
             'local' => 'id_votacion',
             'foreign' => 'id_parlamentario',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}