<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/04/30 19:28:00
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
  'situacion' => 
  array (
    'is_secure' => false,
  ),
  'buscar' => 
  array (
    'is_secure' => false,
  ),
  'filter' => 
  array (
    'is_secure' => false,
  ),
  'balance' => 
  array (
    'is_secure' => false,
  ),
  'balancelist' => 
  array (
    'is_secure' => false,
  ),
  'show2' => 
  array (
    'is_secure' => false,
  ),
  'votaciones' => 
  array (
    'is_secure' => false,
  ),
);
