<?php
// auto-generated by sfViewConfigHandler
// date: 2010/04/30 19:29:57
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Votainteligente - Monitoreo Parlamentario', false, false);
  $response->addMeta('author', 'Gerald Kogler', false, false);
  $response->addMeta('description', 'Vota Inteligente es un proyecto de la fundación Ciudadano Inteligente, que busca promover el accountability y la transparencia', false, false);
  $response->addMeta('keywords', 'vota, votainteligente, Vota Inteligente, elecciones, accountability, transparencia, rendición de cuentas, corrupción, corrupcion, presidenciales, acountability, acontability, piñera, frei, meo, marco, diputados, parlamento, parlamentarios, cámara, senado, legislación, fuentes, comisión, pablo carvacho, participación, ciudadania, ciudadano, sociedad civil, ong, ONG, Chile, chile, financiamiento, sistema electoral, rendición de cuentas, voto, democracia, derecho acceso, derecho información posible, consejo para la transparencia, chile transparente, pro acceso, transparencia internacional, participa, corporacion participa, avina, giro pais UDI, PS, RN, DC, PRSD, PRI, PPD', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('dejoomla.css', '', array ());
  $response->addStylesheet('btn.css', '', array ());


