<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/04/30 19:30:59
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
);
