<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/05/03 10:44:06
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'semana' => 
  array (
    'is_secure' => false,
  ),
);
