<?php

/**
 * Debate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Debate extends BaseDebate
{
  public function __toString()
  {
    return $this->getDateTimeObject('fecha')->format('d/m/Y').': Boletín '.$this->getProyectoLey()->getNroBoletin()." (".$this->getCamara().")";
//return $this->getProyectoLey()->getNroBoletin().' '.$this->getDateTimeObject('fecha')->format('d/m/Y').': Boletín '.$this->getProyectoLey()->getNroBoletin()." (".$this->getCamara().")";
  }
  
  public function getVotacionComisionOrdered()
  {
    $q = Doctrine_Query::create()
      ->select('v.*')
      ->from('VotacionComision v')
      ->where('v.id_debate = ?', $this->getIdDebate())
      ->orderBy('v.tipo ASC');

    return $q->execute();
  }
}
