<?php

/**
 * Materia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Materia extends BaseMateria
{
  public function __toString()
  {
    if ($this->getNombre() != NULL) return $this->getNombre();
    return "";
  }
}
