<?php

/**
 * Region
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Region extends BaseRegion
{
  public function __toString()
  {
    return $this->getNombre();
  }
}
