<?php

/**
 * Votacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vota
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Votacion extends BaseVotacion
{
  public function getVoto($id_parlamentario)
  {
    $voto = Doctrine_Core::getTable('VotacionParlamentario')->find(array($this->getIdVotacion(),$id_parlamentario));
    if ($voto != null) return $voto->getVoto();
    else return null;
  }

  public function getVotosVoto($voto)
  {
    return Doctrine_Core::getTable('VotacionParlamentario')->createQuery('v')->where('v.id_votacion = ?', $this->getIdVotacion())->andWhere('v.voto = ?', $voto)->execute();
  }

  public function getVotosAus()
  {
    ($this->getCamara() == 'C.Diputados') ? $camara='D' : $camara='S';
    $parlamentarios = Doctrine_Core::getTable('Parlamentario')->createQuery('p')->where('p.senador_diputado = ?', $camara)->andWhere('p.activo = ?', 1)->execute();
    $ausentes = new Doctrine_Collection('Parlamentario');
    foreach ($parlamentarios as $i=>$parl){
      if (Doctrine_Core::getTable('VotacionParlamentario')->find(array($this->getIdVotacion(),$parl->getIdParlamentario())) == null) $ausentes->add($parl);
    }
    return $ausentes;
  }

  public function getVotos()
  {
    return Doctrine_Core::getTable('VotacionParlamentario')->createQuery('v')->where('v.id_votacion = ?', $this->getIdVotacion())->execute();
  }

  public function getNota()
  {
    $q = Doctrine_Core::getTable('Votacion')
    ->createQuery('v')
    ->where('v.id_proyecto_ley = ?', $this->getIdProyectoLey())
    ->andWhere('v.visible = ?', 0)
    ->execute();
    return count($q)>0;
  }
}
