<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/10 17:49:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'classname' => 'DoctrinePDO',
  'dsn' => 'mysql:dbname=votainteligente_proyectos;host=localhost',
  'username' => 'vota_p',
  'password' => 'vota_754',
  'encoding' => 'utf8',
  'persistent' => false,
  'pooling' => false,
  'name' => 'doctrine',
)),);
