<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/29 10:32:03
sfConfig::add(array(
  'mod_votacioncomision_enabled' => true,
  'mod_votacioncomision_view_class' => 'sfPHP',
));
